#!/bin/bash

if [ -z "$1" ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
    echo \
        'This command will fix PHP source files based on parameters'
    ./cli/get-git-files --help
    exit
fi

eval $(./cli/get-git-files --php $@)

if [ "$FILES" == "" ]; then
    if grep -Eq '\--format=gitlab' <<< ${PARAMS}; then
        echo "[]"
        exit 0
    fi

    echo "Nenhum arquivo para verificar !"
    exit 0
fi

config=.php-cs-fixer.dist.php
if [[ -f ".php-cs-fixer.php" ]]; then
    config=.php-cs-fixer.php
fi

PHP_CS_FIXER_IGNORE_ENV=1 ./bin/php-cs-fixer fix --config $config $PARAMS $FILES

CS_RETURN="$?"
if grep -Eq '\--format=gitlab' <<< ${PARAMS}; then
    exit $CS_RETURN
fi

if [[ "4" = ${CS_RETURN} ]] || [[ "8" = ${CS_RETURN} ]]; then
    echo ">> Existem arquivos precisando de ajuste, rode o make auto-fix-diff!"
fi

exit $CS_RETURN
