name: "Create Release"

on:
  push:
    branches:
      - stable

jobs:
  php-syntax:
    uses: moveissimonetti/github-actions/.github/workflows/check-php-syntax.yaml@main
    secrets: inherit
    with:
      phpVersion: 8dot3

  lint-container:
    uses: ./.github/workflows/lint-container.yaml
    secrets: inherit

  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Defina a versão do PHP que você está usando

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
